disabled_rules:
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length: 200 
force_cast: warning
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50

